spring:
  banner:
    location: classpath:banner.txt
    charset: UTF-8
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:config-admin}
      password: ${CONFIG_SERVER_PASSWORD}

server:
  port: 8888

---
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: git@github.com:vdechain/config-store.git
          clone-on-start: true
          searchPaths: '{application}'
          force-pull: true
          ignoreLocalSshSettings: true
          privateKey: PUT YOUR KEY

---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/config/{application}
